const Constants = {
  browser: {
    video: {
      // see https://en.wikipedia.org/wiki/Video_file_format
      mimeTypes: ["video/mp4", "video/quicktime"],
      extensions: ["mp4", "mov"],
    },
    image: {
      // see https://github.com/arthurvr/image-extensions/blob/master/image-extensions.json
      mimeTypes: ["image/jpeg", "image/png"],
      extensions: ["jpeg", "jpg", "png"],
    },
    audio: {
      mimeTypes: [
        "audio/wav",
        "audio/x-wav",
        "audio/mpeg",
        "audio/mp3",
        "audio/mpeg3",
        "audio/x-mpeg",
        "audio/x-mp3",
        "audio/x-mpeg3",
      ],
      extensions: ["wav", "mp3"],
    },
  },
  extended: {
    video: {
      mimeTypes: [],
      extensions: [],
    },
    image: {
      mimeTypes: [
        "application/pdf",
        "application/postscript",
        "application/tif",
        "application/tiff",
        "application/vnd.3gpp.pic-bw-small",
        "application/x-pdf",
        "application/x-tif",
        "application/x-tiff",
        "image/avif",
        "image/avif-sequence",
        "image/bmp",
        "image/bmp2",
        "image/bmp3",
        "image/gif",
        "image/heic",
        "image/heif",
        "image/jbg",
        "image/jbig",
        "image/jng",
        "image/jpeg2000",
        "image/jpeg2000-image",
        "image/jxl",
        "image/jxr",
        "image/svg",
        "image/svg+xml",
        "image/tif",
        "image/tiff",
        "image/vnd.adobe.photoshop",
        "image/vnd.radiance",
        "image/webp",
        "image/x-adobe-dng",
        "image/x-canon-cr2",
        "image/x-canon-crw",
        "image/x-canon-raw",
        "image/x-dcraw",
        "image/x-exr",
        "image/x-fuji-raf",
        "image/x-icon",
        "image/x-kodak-dcr",
        "image/x-kodak-k25",
        "image/x-kodak-kdc",
        "image/x-minolta-mrw",
        "image/x-nikon-nef",
        "image/x-olympus-orf",
        "image/x-panasonic-raw",
        "image/x-pentax-pef",
        "image/x-sigma-x3f",
        "image/x-sony-arw",
        "image/x-sony-raw",
        "image/x-sony-sr2",
        "image/x-sony-srf",
        "image/x-targa",
        "image/x-tga",
      ],
      extensions: [
        "arw",
        "avif",
        "avifs",
        "bmp",
        "bmp2",
        "bmp3",
        "cr2",
        "crw",
        "dcr",
        "dng",
        "eps",
        "eps2",
        "eps3",
        "exr",
        "gif",
        "hdr",
        "heic",
        "heif",
        "ico",
        "jbg",
        "jbig",
        "jfif",
        "jng",
        "jp2",
        "jxl",
        "jxr",
        "k25",
        "kdc",
        "mrw",
        "nef",
        "openexr",
        "orf",
        "orf",
        "pdf",
        "pef",
        "ps",
        "ps2",
        "ps3",
        "psb",
        "psd",
        "raf",
        "raf",
        "raw",
        "sr2",
        "srf",
        "svg",
        "tga",
        "tif",
        "tiff",
        "webp",
        "x3f",
      ],
    },
    audio: {
      mimeTypes: [],
      extensions: [],
    },
  },
};

export default Constants;
